name: base
dependencies:
- nvidia::cudatoolkit=11.3.1
- numpy
- pillow
- pip
- python=3.7
- pytorch::pytorch=1.11.0=py3.7_cuda11.3_cudnn8.2.0_0
- tqdm
- gensim
- pip:
  - pillow-simd
  - h5py-cache
  - configargparse
  - cached_property
  - pytorch-ignite
  - regex
  - wandb
  - PyYAML>=5.1
  - sacrebleu
  - rouge-score
  - transformers==4.2.0
  - fairscale
  - accelerate
  - sentencepiece!=0.1.92
  - nltk
