name: base
dependencies:
- nvidia::cudatoolkit=9.2.148
- numpy
- pillow
- pip
- python=3.6
- pytorch::pytorch=0.4.1=py36_cuda9.2.148_cudnn7.1.4_1
- scipy
- tqdm
- scikit-learn
- gensim
- pandas
- tensorboard
- tensorboardX
- pip:
  - pillow-simd
  - h5py-cache
  - configargparse
  - sacrebleu
  - rouge-score
  - nltk
