name: base
dependencies:
- nvidia::cudatoolkit=10.0.130
- numpy
- pillow
- pip
- python=3.6
- pytorch::pytorch=1.0.1=py3.6_cuda10.0.130_cudnn7.4.2_2
- scipy
- tqdm
- scikit-learn
- gensim
- pandas
- tensorboard
- tensorboardX
- pip:
  - pillow-simd
  - h5py-cache
  - configargparse
  - sacrebleu
  - rouge-score
  - nltk
