name: base
dependencies:
- nvidia::cudatoolkit=10.2.89
- numpy
- pillow
- pip
- python=3.8
- pytorch::pytorch=1.8.1=py3.8_cuda10.2_cudnn7.6.5_0
- scipy
- tqdm
- scikit-learn
- gensim
- pandas
- tensorboard
- tensorboardX
- pip:
  - pillow-simd
  - h5py-cache
  - configargparse
  - sacrebleu
  - rouge-score
  - datasets==1.16
  - transformers==4.10.0
  - pytorch-lightning==1.5.0
  - nltk
