name: base
dependencies:
- nvidia::cudatoolkit=10.2.89
- numpy
- pillow
- pip
- python=3.8
- pytorch::pytorch=1.7.1=py3.8_cuda10.2.89_cudnn7.6.5_0
- scipy
- tqdm
- scikit-learn
- gensim
- pandas
- tensorboard
- tensorboardX
- pip:
  - pillow-simd
  - h5py-cache
  - configargparse
  - sacrebleu
  - rouge-score
  - nltk
  - pytorch_pretrained_bert==0.6.2
