name: base
dependencies:
- nvidia::cudatoolkit=11.3.1
- numpy
- pillow
- pip
- python=3.8
- pytorch::pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
- scipy
- tqdm
- scikit-learn
- gensim
- pandas
- pip:
  - pillow-simd
  - h5py-cache
  - configargparse
  - sacrebleu
  - rouge-score
  - datasets==1.11
  - transformers==4.8.2
  - pytorch-lightning==1.4.5
  - nltk
